namespace: microservices

replicaCount: 2

image:
  user:
    repository: 076124125794.dkr.ecr.us-east-1.amazonaws.com/user-service
    tag: latest

  product:
    repository: 076124125794.dkr.ecr.us-east-1.amazonaws.com/product-service
    tag: latest

  order:
    repository: 076124125794.dkr.ecr.us-east-1.amazonaws.com/order-service
    tag: latest

database:
  host: pharma-dev-postgres.c8zsmesiuilk.us-east-1.rds.amazonaws.com
  port: 5432
  username: pharmaadmin
  password: MySecurePassword123!
  database: pharmadb