name: Build Push Deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Build User Image
        run: |
          docker build -t user-service:${{ github.sha }} ./user-service

      - name: Build Product Image
        run: |
          docker build -t product-service:${{ github.sha }} ./product-service

      - name: Build Order Image
        run: |
          docker build -t order-service:${{ github.sha }} ./order-service

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
          --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Helm Deploy
        run: |
          helm upgrade --install microservices \
          ./helm/microservices \
          --set image.user.tag=${{ github.sha }} \
          --set image.product.tag=${{ github.sha }} \
          --set image.order.tag=${{ github.sha }}